language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: nightly

sudo: false

install:
  - travis_retry composer update --no-progress --prefer-dist --profile

script:
  - composer test

  
